//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDemo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryTransaction
    {
        public long LibraryTransactionId { get; set; }
        public short TransactionTypeId { get; set; }
        public Nullable<long> BookId { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual LibraryTransactionType LibraryTransactionType { get; set; }
    }
}
